# Generated by Django 4.1.3 on 2022-11-08 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
