# Generated by Django 4.1.3 on 2022-11-10 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('repeat_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('items', models.ManyToManyField(related_name='sports_items', to='app_sport.itemsport')),
                ('members', models.ManyToManyField(related_name='sports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
