# Generated by Django 4.1.3 on 2022-11-10 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sports', to=settings.AUTH_USER_MODEL),
        ),
    ]
