# Generated by Django 4.1.3 on 2022-11-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_score', '0002_alter_score_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='month',
            field=models.DateField(unique=True),
        ),
    ]
